stages:
  - test
  - build

test:
  stage: test
  tags:
    - gitlab-nks
  script:
    - echo "=====test====="

docker-build:
  stage: build
  image: docker:latest
  tags:
    - gitlab-nks
  services:
    - docker:dind
  script:
    - docker build . -t $NKS_CR_URL/gitlab-nks:$CI_COMMIT_SHA -t $NKS_CR_URL/gitlab-nks:latest
    - docker login -u $NKS_ACCESS_ID -p $NKS_ACCESS_PASSWORD $NKS_CR_URL
    - docker push $NKS_CR_URL/gitlab-nks:$CI_COMMIT_SHA
    - docker push $NKS_CR_URL/gitlab-nks:latest
