apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-nks-deployment
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: lalll5555/gitlab-nks:latest
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Servicemetadata:
  name: gitlab-nks-service
  namespace: gitlab
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: apache
  type: NodePort

